[versions]

androidxCore = "1.12.0"
androidxLifecycle = "2.7.0"
androidxActivity = "1.8.2"
androidxTestExt = "1.1.5"
androidxTestEspresso = "3.5.1"
androidxNavigation = "2.7.7"
androidxHilt = "1.2.0"
androidxStartup = "1.1.1"
androidxMedia3 = "1.2.1"
androidxBrowser = "1.7.0"
androidxWindow = "1.2.0"
androidDesugar = "2.0.4"

compose = "1.7.0-alpha02"
composeCompiler = "1.5.8"
composeShadowsPlus = "1.0.4"
constraintlayoutCompose = "1.0.1"
material3 = "1.2.0"
okhttp3 = "4.12.0"
retrofit2 = "2.9.0"
room = "2.6.1"
kotlinxSerializationConverter = "1.0.0"
loggingInterceptor = "4.11.0"
networkresultCalladapter = "1.0.0"

kotlinxDatetime = "0.5.0"
kotlinxSerializationJson = "1.6.2"
kotlinxCollections = "0.3.7"
kotlinxCoroutines = "1.7.3"
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"
ktsoup = "0.3.0"

agp = "8.3.0"
coil = "2.4.0"
media = "0.4.0"
mmkv = "1.3.2"
mockk = "1.13.8"
mockitoKotlin = "5.1.0"
lottie = "6.0.0"
work = "2.9.0"
leakcanary = "2.12"
composeDestinations = "1.10.0"
hilt = "2.50"
haze = "0.5.2"
googleServices = "4.4.1"
firebase = "32.7.3"
firebaseCrashlyticsPlugin = "2.9.9"
paging3 = "3.2.1"
splashScreen = "1.0.1"
junit = "4.13.2"
robolectric = "4.11.1"
jsoup = "1.16.1"
zoomimage = "1.0.0-beta10"
uiautomator = "2.3.0"
benchmark-macro-junit4 = "1.2.3"
profileinstaller = "1.3.1"
monitor = "1.6.1"
junitKtx = "1.1.5"
logcat = "0.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidxBrowser" }
androidx-media3 = { module = "androidx.media3:media3-exoplayer", version.ref = "androidxMedia3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "androidxMedia3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "androidDesugar" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidxWindow" }

androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }

splash = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }

okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp3" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinxSerializationConverter" }
networkresult-calladapter = { module = "at.connyduck:networkresult-calladapter", version.ref = "networkresultCalladapter" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
logcat = { module = "com.squareup.logcat:logcat", version.ref = "logcat" }

ktsoup-core = { module = "org.drewcarlson:ktsoup-core", version.ref = "ktsoup" }
ktsoup-fx = { module = "org.drewcarlson:ktsoup-fs", version.ref = "ktsoup" }

constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

com-google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
com-google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartup" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
compose-media = { module = "com.github.fengdai.compose:media", version.ref = "media" }
zoomable = { module = "io.github.panpf.zoomimage:zoomimage-compose-coil", version.ref = "zoomimage" }
lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
compose-destinations-animations-core = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "composeDestinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "composeDestinations" }
compose-shadow-plus = { module = "com.github.GIGAMOLE:ComposeShadowsPlus", version.ref = "composeShadowsPlus" }

org-jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollections" }

androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging3" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging3" }

work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
work-testing = { module = "androidx.work:work-testing", version.ref = "work" }

android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
androidx-monitor = { group = "androidx.test", name = "monitor", version.ref = "monitor" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
